### ISSUE TITLE
event length, amount of attendees & costs

### ISSUE THREAD

**Issue by robertkowalski** [jsunconf/conf-bootstrap#1]
they all relate to each other.

if you run just run a one day event instead of 2 days you have almost half of the costs as location and food are the most expensive things.

that means you only have to come up with half of the sponsors.

some numbers i have from previous unconfs:

```
CouchDB Day    100 attendees   1 day     6.000€
JS Unconf      300 attendees   2 days   40.000€
```

**Comment by klyrr** [comment]
Fixed with https://github.com/jsunconf/conf-bootstrap/commit/a8007d4c10e440ef7633270f94a6204ea2bb9971
